# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a00eb774e1d61405d09f3381a55cdd301da95652357bd39748345a8d527dfae5ad0676f74acc5cf9c7f277745f5dd320941d17b02192ee6677b66abb960e02ee

test:
  secret_key_base: f4fc4c492a9e719252f7d1d184184c37fc37e36338a3174461d85b4a7c192b4d44c92576dffb6802d5c45169095296ee087a0dbc9b71d012f36f719a78e9367c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
